jobs:
  - job: ubuntu_1604_hosted
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      system.debug: true
    
    steps:

    - checkout: self
      submodules: recursive

    - script: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt -y update
        sudo apt install g++-9 ninja-build -y

    - task: CacheBeta@0
      displayName: Cache vcpkg artifacts
      inputs:
        key: $(Build.SourcesDirectory)/vcpkg_ports_unix.txt| $(Build.SourcesDirectory)/.git/modules/vcpkg/HEAD | "$(Agent.OS)"
        path: '$(Build.SourcesDirectory)/vcpkg'

    - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
      displayName: 'Run vcpkg'
      inputs:
        vcpkgTriplet: 'x64-linux'
        vcpkgArguments: '@$(Build.SourcesDirectory)/vcpkg_ports.txt @$(Build.SourcesDirectory)/vcpkg_ports_unix.txt' 
        vcpkgDirectory: $(Build.SourcesDirectory)/vcpkg

    - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
      displayName: 'Run CMake and Ninja - CMakeLists.txt'
      inputs:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: CMakeLists.txt
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release'

    - script: |
        cd $(Build.ArtifactStagingDirectory)/Release/Binaries/
        ./test_runner *test.so
      displayName: 'Run tests, release'
